# Generated by Django 4.2 on 2023-04-20 07:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("namespace", models.CharField(blank=True, max_length=256)),
                ("name", models.CharField(blank=True, max_length=256)),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipPersonPlace",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("namespace", models.CharField(max_length=256)),
                (
                    "relationship_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            ("1", "Family"),
                            ("2", "Personal"),
                            ("3", "Professional"),
                            ("4", "Public"),
                        ],
                        default="2",
                    ),
                ),
                ("relationship_sentiment", models.FloatField(default=0.0)),
                ("relationship_notes", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memory_graph.person",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memory_graph.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipPersonPerson",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("namespace", models.CharField(max_length=256)),
                (
                    "relationship_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            ("1", "Family"),
                            ("2", "Personal"),
                            ("3", "Professional"),
                            ("4", "Public"),
                        ],
                        default="2",
                    ),
                ),
                ("relationship_sentiment", models.FloatField(default=0.0)),
                ("relationship_notes", models.TextField(blank=True)),
                (
                    "person1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="person1",
                        to="memory_graph.person",
                    ),
                ),
                (
                    "person2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="person2",
                        to="memory_graph.person",
                    ),
                ),
            ],
        ),
    ]
