# Generated by Django 4.2 on 2023-04-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_userprofile_bio_userprofile_profile_text"),
        ("memory_graph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[("1", "Male"), ("3", "Female")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="profile_id",
            field=models.OneToOneField(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.userprofile",
            ),
            preserve_default=False,
        ),
    ]
