# Generated by Django 4.2 on 2023-04-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_userprofile_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_text",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
